// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

import ServiceA from '../workers/service-a/src/index';
import ServiceB from '../workers/service-b/src/index';

interface Env {
	SERVICE_A: Service<ServiceA>;
	SERVICE_B: Service<ServiceB>;
}
