#:schema node_modules/wrangler/config-schema.json
name = "service-a"
main = "src/index.ts"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[dev]
port = 10100

[observability]
enabled = true
