// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
import ServiceA from '../service-a/src/index';

interface Env {
	SERVICE_A: Service<ServiceA>;
}
