#:schema node_modules/wrangler/config-schema.json
name = "service-b"
main = "src/index.ts"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[dev]
port = 10200

[observability]
enabled = true

[[services]]
binding = "SERVICE_A"
service = "service-a"